name = "lnkd-world"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "49f9ff9f41b126b2660f84ba1b10ac33"

assets = { directory = ".open-next/assets", binding = "ASSETS" }

routes = [
  { pattern = "lnkd.world", custom_domain = true },
]

[vars]
NEXT_PUBLIC_CONVEX_URL = "https://steady-butterfly-270.convex.cloud"
