#!/usr/bin/env node
/*
 * build-feed.mjs — Publish your 3 Cowork artifacts as a login-gated "/feed".
 *
 * It reads the latest generated HTML for each artifact, strips the Cowork-only
 * controls (the "Refresh now" button + reload hints), keeps the content and the
 * Copy buttons, builds a small hub page, and writes each page as a TypeScript
 * module under <repo>/feed-content/ (NOT public/). Those modules are imported by
 * the authenticated route handler app/feed/view/[slug]/route.ts, which serves the
 * HTML only to logged-in users. Keeping the HTML out of public/ is what makes the
 * gate real — nothing is fetchable without auth, on Cloudflare Workers included.
 *
 * Your existing scheduled tasks keep regenerating the artifacts as normal — this
 * script just snapshots the latest versions onto your site when you choose.
 *
 * USAGE
 *   1. Edit SITE_REPO below (or pass it as an env var).
 *   2. Run:        SITE_REPO=/path/to/your/site node build-feed.mjs
 *      Auto-push:  SITE_REPO=/path/to/your/site GIT_PUSH=1 node build-feed.mjs
 *
 * No dependencies — plain Node (v16+).
 */

import fs from 'fs';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';

// ---------- CONFIG (edit these, or pass as env vars) ----------
const SITE_REPO  = process.env.SITE_REPO  || '/path/to/your/site';                 // your Next.js / React repo root
const CONTENT_DIR = process.env.CONTENT_DIR || 'convex/feedPages';                   // served by the gated Convex query
const ARTIFACTS  = process.env.ARTIFACTS_DIR || path.join(os.homedir(), 'Documents', 'Claude', 'Artifacts');
const GIT_PUSH   = process.env.GIT_PUSH === '1';                                     // set GIT_PUSH=1 to commit (record only)
// --------------------------------------------------------------

// Each artifact → URL slug + module name. The cleaned HTML is written as a TS
// module that convex/feed.ts imports and serves to logged-in users. NOTE: Convex
// module filenames may not contain hyphens (alphanumeric/underscore/period only),
// so `mod` is the hyphen-free file stem while `slug` stays the hyphenated URL.
const PAGES = [
  { id: 'contentious-health-longevity-news', slug: 'contentious-news', mod: 'contentiousNews' },
  { id: 'x-trends-startups-health-longevity', slug: 'x-trends', mod: 'xTrends' },
  { id: 'x-reply-opportunities', slug: 'reply-radar', mod: 'replyRadar' },
];

const OUT_DIR = path.join(SITE_REPO, CONTENT_DIR);

function resolveSource(id) {
  // Default Cowork layout: <Artifacts>/<id>/index.html
  const nested = path.join(ARTIFACTS, id, 'index.html');
  if (fs.existsSync(nested)) return nested;
  // Fallback: a flat file named <id>.html or the out name in ARTIFACTS (useful for testing)
  const flat = path.join(ARTIFACTS, id + '.html');
  if (fs.existsSync(flat)) return flat;
  return null;
}

// Remove Cowork-only UI; keep content + Copy buttons.
function cleanForWeb(html) {
  // Structural removals: the refresh button row + the expand/refresh hint line.
  let out = html
    .replace(/<div class="controls">[\s\S]*?<\/div>/, '')
    .replace(/<div class="hint">[\s\S]*?<\/div>/, '');

  // Strip Cowork-only prose sentences, but NEVER touch <script>…</script> blocks
  // (the broad sentence regex would otherwise corrupt JS string literals and the
  // JSON metadata block, which only stayed valid before by lucky boundaries).
  out = out
    .split(/(<script[\s\S]*?<\/script>)/i)
    .map((seg) =>
      seg.slice(0, 7).toLowerCase() === '<script'
        ? seg
        : seg
            // seed-banner instruction that wraps "Refresh now" in <b> tags (Reply Radar)
            .replace(/Press\s*<b>\s*↻?\s*Refresh now\s*<\/b>[^.<]*\.\s*/gi, '')
            // any remaining sentence referencing the Cowork Refresh/Reload buttons
            .replace(/[^.<>]*(?:Reload button|Refresh now)[^.<>]*\.\s*/g, '')
    )
    .join('');

  // Neutralize the now-orphaned Cowork JS: setStatus referenced the removed
  // #status element, and refresh called window.cowork. Neither is reachable once
  // the Refresh button is gone. Both replacements fail safe — if the artifact's
  // shape ever changes they simply don't match and the code is left as-is.
  out = out
    .replace(/function setStatus\(msg\)\{[^}]*\}/, 'function setStatus(){}')
    .replace(
      /(?:async\s+)?function refresh\s*\([\s\S]*?(?=\n\s*function\s+(?:copyTweet|copyReply)\b)/,
      'function refresh(){}\n  '
    );

  return out.trim();
}

// Wrap a cleaned HTML string as an auto-generated TS module imported by convex/feed.ts.
function toModule(html) {
  return `// AUTO-GENERATED by scripts/build-feed.mjs — do not edit by hand.\nexport default ${JSON.stringify(html)};\n`;
}

// ---------- run ----------
fs.mkdirSync(OUT_DIR, { recursive: true });

const published = [];
for (const p of PAGES) {
  const src = resolveSource(p.id);
  if (!src) { console.warn(`! skip ${p.id} — source not found under ${ARTIFACTS}`); continue; }
  const html = cleanForWeb(fs.readFileSync(src, 'utf8'));
  fs.writeFileSync(path.join(OUT_DIR, `${p.mod}.ts`), toModule(html));
  published.push(p);
  console.log(`✓ ${p.mod}.ts  ←  ${src}`);
}

if (published.length === 0) {
  console.error('No artifacts found. Check ARTIFACTS_DIR.'); process.exit(1);
}

if (GIT_PUSH) {
  try {
    execSync(`git -C "${SITE_REPO}" add "${CONTENT_DIR}"`, { stdio: 'inherit' });
    execSync(`git -C "${SITE_REPO}" commit -m "feed: publish snapshot ${new Date().toISOString()}"`, { stdio: 'inherit' });
    console.log('✓ committed (record only — deploy with `npx convex deploy`)');
  } catch (e) {
    console.error('git step failed (nothing to commit):', e.message);
  }
}

console.log(`\nDone. Wrote ${published.length} page module(s) to ${OUT_DIR}`);
console.log('Publish to production with:  npx convex deploy   (content is served by the gated Convex query)');
